services:

  metrocali-data-quality-api:
    image: metrocali-data-quality-api:1.0.0
    container_name: api
    ports:
      - "8001:8000" # se tiene otro servicio con el puerto 8000
    env_file:
      - .env.api
    networks:
      - data_quality_network
    depends_on:
      - valkey

  metrocali-data-quality-worker-catalog:
    image: metrocali-data-quality-worker-catalog:1.0.0
    container_name: worker_catalog
    env_file:
      - .env.worker
    restart: "no"
    networks:
      - data_quality_network
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:8-alpine
    container_name: local_valkey
    ports:
      - "6379:6379"
    networks:
      - data_quality_network

networks:
  data_quality_network:
    name: metrocali_network
    driver: bridge